spring.application.name=oreo
spring.datasource.url=jdbc:postgresql://localhost:5432/hr_system
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.security.user.name=admin
spring.security.user.password=nimda