spring.application.name=oreo
spring.datasource.url=jdbc:postgresql://localhost:5432/hr_system
spring.datasource.username=postgres
spring.datasource.password=password
# comment before running first time, then un-comment after
# spring.sql.init.mode=always
# disable in prod use (validate) / use create to init table (warning will destroy all data)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# enable in production
spring.flyway.enabled=false
spring.flyway.locations=classpath:db/migration
spring.security.user.name=admin
spring.security.user.password=nimda
spring.security.user.roles=ADMIN
server.port=8081
