--
-- PostgreSQL database dump
--

--
-- TOC entry 227 (class 1259 OID 17379)
-- Name: allowance_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.allowance_type
(
    taxable       boolean,
    creation_time timestamp(6) without time zone,
    id            bigint NOT NULL,
    modified_time timestamp(6) without time zone,
    created_by    character varying(255),
    name          character varying(255),
    updated_by    character varying(255)
);


ALTER TABLE public.allowance_type OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 17372)
-- Name: allowance_type_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.allowance_type_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE CACHE 1;


ALTER SEQUENCE public.allowance_type_seq OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 17388)
-- Name: attendance; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.attendance
(
    date           date,
    late_minutes   integer,
    overtime_hours double precision,
    time_in        time(6) without time zone,
    time_out       time(6) without time zone,
    under_time     boolean NOT NULL,
    worked_hours   double precision,
    creation_time  timestamp(6) without time zone,
    employee_id    bigint,
    id             bigint  NOT NULL,
    modified_time  timestamp(6) without time zone,
    created_by     character varying(255),
    updated_by     character varying(255)
);


ALTER TABLE public.attendance OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 17387)
-- Name: attendance_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.attendance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 17398)
-- Name: attendance_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.attendance_log
(
    biometric_device_id bigint,
    creation_time       timestamp(6) without time zone,
    employee_id         bigint,
    id                  bigint NOT NULL,
    modified_time       timestamp(6) without time zone,
    "timestamp"         timestamp(6) without time zone,
    created_by          character varying(255),
    device_id           character varying(255),
    type                character varying(255),
    updated_by          character varying(255)
);


ALTER TABLE public.attendance_log OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 17397)
-- Name: attendance_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.attendance_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 17407)
-- Name: deduction_bracket; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.deduction_bracket
(
    contribution      double precision,
    max_salary        double precision,
    min_salary        double precision,
    deduction_type_id bigint,
    id                bigint NOT NULL
);


ALTER TABLE public.deduction_bracket OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 17406)
-- Name: deduction_bracket_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.deduction_bracket ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deduction_bracket_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 235 (class 1259 OID 17414)
-- Name: deduction_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.deduction_type
(
    mandatory boolean,
    rate      double precision,
    id        bigint NOT NULL,
    name      character varying(255)
);


ALTER TABLE public.deduction_type OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 17413)
-- Name: deduction_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.deduction_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.deduction_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 17421)
-- Name: department; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.department
(
    creation_time timestamp(6) without time zone,
    id            bigint                 NOT NULL,
    modified_time timestamp(6) without time zone,
    code          character varying(255) NOT NULL,
    created_by    character varying(255),
    description   character varying(255),
    name          character varying(255),
    updated_by    character varying(255)
);


ALTER TABLE public.department OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 17420)
-- Name: department_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.department ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.department_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 238 (class 1259 OID 17432)
-- Name: device; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.device
(
    id         bigint NOT NULL,
    ip_address character varying(255),
    location   character varying(255),
    name       character varying(255)
);


ALTER TABLE public.device OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 17373)
-- Name: device_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.device_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE CACHE 1;


ALTER SEQUENCE public.device_seq OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 17441)
-- Name: employee; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee
(
    creation_time            timestamp(6) without time zone,
    department_id            bigint,
    id                       bigint NOT NULL,
    modified_time            timestamp(6) without time zone,
    payroll_schedule_code_id bigint,
    position_id              bigint,
    created_by               character varying(255),
    email                    character varying(255),
    employee_code            character varying(255),
    first_name               character varying(255),
    hire_date                character varying(255),
    last_name                character varying(255),
    phone                    character varying(255),
    status                   character varying(255),
    updated_by               character varying(255)
);


ALTER TABLE public.employee OWNER TO postgres;

--
-- TOC entry 241 (class 1259 OID 17449)
-- Name: employee_allowance; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee_allowance
(
    amount            double precision,
    allowance_type_id bigint,
    creation_time     timestamp(6) without time zone,
    employee_id       bigint,
    id                bigint NOT NULL,
    modified_time     timestamp(6) without time zone,
    created_by        character varying(255),
    updated_by        character varying(255)
);


ALTER TABLE public.employee_allowance OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 17374)
-- Name: employee_allowance_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.employee_allowance_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE CACHE 1;


ALTER SEQUENCE public.employee_allowance_seq OWNER TO postgres;

--
-- TOC entry 239 (class 1259 OID 17440)
-- Name: employee_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employee ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 243 (class 1259 OID 17458)
-- Name: employee_leave; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee_leave
(
    leave_date    date,
    paid          boolean,
    creation_time timestamp(6) without time zone,
    employee_id   bigint,
    id            bigint NOT NULL,
    leave_type_id bigint,
    modified_time timestamp(6) without time zone,
    created_by    character varying(255),
    updated_by    character varying(255)
);


ALTER TABLE public.employee_leave OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 17457)
-- Name: employee_leave_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employee_leave ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_leave_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 245 (class 1259 OID 17467)
-- Name: employee_salary; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.employee_salary
(
    base_salary       numeric(38, 2),
    effective_date    date,
    creation_time     timestamp(6) without time zone,
    employee_id       bigint,
    id                bigint NOT NULL,
    modified_time     timestamp(6) without time zone,
    over_time_rule_id bigint,
    tax_rule_id       bigint,
    created_by        character varying(255),
    updated_by        character varying(255)
);


ALTER TABLE public.employee_salary OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 17466)
-- Name: employee_salary_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.employee_salary ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.employee_salary_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 17477)
-- Name: holiday; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.holiday
(
    date          date,
    multiplier    double precision,
    creation_time timestamp(6) without time zone,
    id            bigint NOT NULL,
    modified_time timestamp(6) without time zone,
    created_by    character varying(255),
    name          character varying(255),
    type          character varying(255),
    updated_by    character varying(255),
    CONSTRAINT holiday_type_check CHECK (((type)::text = ANY ((ARRAY['REGULAR':: character varying, 'SPECIAL':: character varying])::text[])
) )
);


ALTER TABLE public.holiday OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 17375)
-- Name: holiday_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.holiday_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE CACHE 1;


ALTER SEQUENCE public.holiday_seq OWNER TO postgres;

--
-- TOC entry 247 (class 1259 OID 17486)
-- Name: leave_request; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.leave_request
(
    days          integer,
    end_date      date,
    start_date    date,
    creation_time timestamp(6) without time zone,
    employee_id   bigint,
    id            bigint NOT NULL,
    leave_type_id bigint,
    modified_time timestamp(6) without time zone,
    created_by    character varying(255),
    reason        character varying(255),
    status        character varying(255),
    updated_by    character varying(255),
    CONSTRAINT leave_request_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING':: character varying, 'APPROVED':: character varying, 'REJECTED':: character varying])::text[])
) )
);


ALTER TABLE public.leave_request OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 17376)
-- Name: leave_request_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.leave_request_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE CACHE 1;


ALTER SEQUENCE public.leave_request_seq OWNER TO postgres;

--
-- TOC entry 248 (class 1259 OID 17495)
-- Name: leave_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.leave_type
(
    is_paid           boolean,
    max_days_per_year integer,
    creation_time     timestamp(6) without time zone,
    id                bigint NOT NULL,
    modified_time     timestamp(6) without time zone,
    created_by        character varying(255),
    name              character varying(255),
    updated_by        character varying(255)
);


ALTER TABLE public.leave_type OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 17377)
-- Name: leave_type_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.leave_type_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE CACHE 1;


ALTER SEQUENCE public.leave_type_seq OWNER TO postgres;

--
-- TOC entry 250 (class 1259 OID 17504)
-- Name: over_time_rule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.over_time_rule
(
    multiplier    double precision,
    creation_time timestamp(6) without time zone,
    id            bigint NOT NULL,
    modified_time timestamp(6) without time zone,
    created_by    character varying(255),
    description   character varying(255),
    name          character varying(255),
    updated_by    character varying(255)
);


ALTER TABLE public.over_time_rule OWNER TO postgres;

--
-- TOC entry 249 (class 1259 OID 17503)
-- Name: over_time_rule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.over_time_rule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.over_time_rule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 251 (class 1259 OID 17512)
-- Name: payroll; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payroll
(
    basic_salary      numeric(38, 2),
    gross_salary      numeric(38, 2),
    holiday_pay       numeric(38, 2),
    late_deduction    numeric(38, 2),
    leave_deduction   numeric(38, 2),
    net_salary        numeric(38, 2),
    overtime_pay      numeric(38, 2),
    pagibig           numeric(38, 2),
    phil_health       numeric(38, 2),
    sss               numeric(38, 2),
    tax               numeric(38, 2),
    total_allowance   numeric(38, 2),
    creation_time     timestamp(6) without time zone,
    employee_id       bigint,
    id                bigint NOT NULL,
    modified_time     timestamp(6) without time zone,
    payroll_period_id bigint,
    created_by        character varying(255),
    updated_by        character varying(255)
);


ALTER TABLE public.payroll OWNER TO postgres;

--
-- TOC entry 253 (class 1259 OID 17521)
-- Name: payroll_period; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payroll_period
(
    end_date      date,
    start_date    date,
    creation_time timestamp(6) without time zone,
    id            bigint NOT NULL,
    modified_time timestamp(6) without time zone,
    created_by    character varying(255),
    status        character varying(255),
    updated_by    character varying(255),
    CONSTRAINT payroll_period_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN':: character varying, 'CLOSED':: character varying, 'PROCESSED':: character varying])::text[])
) )
);


ALTER TABLE public.payroll_period OWNER TO postgres;

--
-- TOC entry 252 (class 1259 OID 17520)
-- Name: payroll_period_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payroll_period ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payroll_period_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16928)
-- Name: payroll_run_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.payroll_run_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE CACHE 1;


ALTER SEQUENCE public.payroll_run_seq OWNER TO postgres;

--
-- TOC entry 255 (class 1259 OID 17531)
-- Name: payroll_schedule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.payroll_schedule
(
    creation_time timestamp(6) without time zone,
    id            bigint NOT NULL,
    modified_time timestamp(6) without time zone,
    created_by    character varying(255),
    name          character varying(255),
    pay_days      character varying(255),
    payroll_type  character varying(255),
    updated_by    character varying(255),
    CONSTRAINT payroll_schedule_payroll_type_check CHECK (((payroll_type)::text = ANY ((ARRAY['WEEKLY':: character varying, 'SEMI_MONTHLY':: character varying, 'MONTHLY':: character varying, 'DAILY':: character varying])::text[])
) )
);


ALTER TABLE public.payroll_schedule OWNER TO postgres;

--
-- TOC entry 254 (class 1259 OID 17530)
-- Name: payroll_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.payroll_schedule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payroll_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 17378)
-- Name: payroll_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.payroll_seq
    START WITH 1
    INCREMENT BY 50
    NO MINVALUE
    NO MAXVALUE CACHE 1;


ALTER SEQUENCE public.payroll_seq OWNER TO postgres;

--
-- TOC entry 257 (class 1259 OID 17541)
-- Name: position; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."position"
(
    creation_time timestamp(6) without time zone,
    id            bigint NOT NULL,
    modified_time timestamp(6) without time zone,
    created_by    character varying(255),
    description   character varying(255),
    title         character varying(255),
    updated_by    character varying(255)
);


ALTER TABLE public."position" OWNER TO postgres;

--
-- TOC entry 256 (class 1259 OID 17540)
-- Name: position_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."position" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.position_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 259 (class 1259 OID 17550)
-- Name: system_settings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.system_settings
(
    id            bigint NOT NULL,
    description   character varying(255),
    setting_key   character varying(255),
    setting_value character varying(255)
);


ALTER TABLE public.system_settings OWNER TO postgres;

--
-- TOC entry 258 (class 1259 OID 17549)
-- Name: system_settings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.system_settings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.system_settings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 261 (class 1259 OID 17561)
-- Name: tax_rule; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tax_rule
(
    rate          double precision,
    creation_time timestamp(6) without time zone,
    id            bigint NOT NULL,
    modified_time timestamp(6) without time zone,
    created_by    character varying(255),
    description   character varying(255),
    name          character varying(255),
    updated_by    character varying(255)
);


ALTER TABLE public.tax_rule OWNER TO postgres;

--
-- TOC entry 260 (class 1259 OID 17560)
-- Name: tax_rule_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tax_rule ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tax_rule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

