CREATE SEQUENCE IF NOT EXISTS allowance_type_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS device_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS employee_allowance_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS holiday_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS leave_request_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS leave_type_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS payroll_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE allowance_type
(
    id            BIGINT NOT NULL,
    creation_time TIMESTAMP WITHOUT TIME ZONE,
    modified_time TIMESTAMP WITHOUT TIME ZONE,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    name          VARCHAR(255),
    taxable       BOOLEAN,
    CONSTRAINT pk_allowancetype PRIMARY KEY (id)
);

CREATE TABLE attendance
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_time  TIMESTAMP WITHOUT TIME ZONE,
    modified_time  TIMESTAMP WITHOUT TIME ZONE,
    created_by     VARCHAR(255),
    updated_by     VARCHAR(255),
    employee_id    BIGINT,
    date           date,
    time_in        time WITHOUT TIME ZONE,
    time_out       time WITHOUT TIME ZONE,
    worked_hours   DOUBLE PRECISION,
    overtime_hours DOUBLE PRECISION,
    late_minutes   INTEGER,
    under_time     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_attendance PRIMARY KEY (id)
);

CREATE TABLE attendance_log
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_time       TIMESTAMP WITHOUT TIME ZONE,
    modified_time       TIMESTAMP WITHOUT TIME ZONE,
    created_by          VARCHAR(255),
    updated_by          VARCHAR(255),
    employee_id         BIGINT,
    biometric_device_id BIGINT,
    timestamp           TIMESTAMP WITHOUT TIME ZONE,
    device_id           VARCHAR(255),
    type                VARCHAR(255),
    CONSTRAINT pk_attendancelog PRIMARY KEY (id)
);

CREATE TABLE deduction_bracket
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    deduction_type_id BIGINT,
    min_salary        DOUBLE PRECISION,
    max_salary        DOUBLE PRECISION,
    contribution      DOUBLE PRECISION,
    CONSTRAINT pk_deductionbracket PRIMARY KEY (id)
);

CREATE TABLE deduction_type
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    mandatory BOOLEAN,
    rate      DOUBLE PRECISION,
    CONSTRAINT pk_deductiontype PRIMARY KEY (id)
);

CREATE TABLE department
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_time TIMESTAMP WITHOUT TIME ZONE,
    modified_time TIMESTAMP WITHOUT TIME ZONE,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    code          VARCHAR(255)                            NOT NULL,
    name          VARCHAR(255),
    description   VARCHAR(255),
    CONSTRAINT pk_department PRIMARY KEY (id)
);

CREATE TABLE device
(
    id         BIGINT NOT NULL,
    name       VARCHAR(255),
    location   VARCHAR(255),
    ip_address VARCHAR(255),
    CONSTRAINT pk_device PRIMARY KEY (id)
);

CREATE TABLE employee
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_time            TIMESTAMP WITHOUT TIME ZONE,
    modified_time            TIMESTAMP WITHOUT TIME ZONE,
    created_by               VARCHAR(255),
    updated_by               VARCHAR(255),
    employee_code            VARCHAR(255),
    department_id            BIGINT,
    position_id              BIGINT,
    payroll_schedule_code_id BIGINT,
    first_name               VARCHAR(255),
    last_name                VARCHAR(255),
    email                    VARCHAR(255),
    status                   VARCHAR(255),
    phone                    VARCHAR(255),
    hire_date                date,
    CONSTRAINT pk_employee PRIMARY KEY (id)
);

CREATE TABLE employee_allowance
(
    id                BIGINT NOT NULL,
    creation_time     TIMESTAMP WITHOUT TIME ZONE,
    modified_time     TIMESTAMP WITHOUT TIME ZONE,
    created_by        VARCHAR(255),
    updated_by        VARCHAR(255),
    employee_id       BIGINT,
    allowance_type_id BIGINT,
    amount            DOUBLE PRECISION,
    CONSTRAINT pk_employeeallowance PRIMARY KEY (id)
);

CREATE TABLE employee_leave
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_time TIMESTAMP WITHOUT TIME ZONE,
    modified_time TIMESTAMP WITHOUT TIME ZONE,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    employee_id   BIGINT,
    leave_type_id BIGINT,
    leave_date    date,
    paid          BOOLEAN,
    CONSTRAINT pk_employeeleave PRIMARY KEY (id)
);

CREATE TABLE employee_salary
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_time     TIMESTAMP WITHOUT TIME ZONE,
    modified_time     TIMESTAMP WITHOUT TIME ZONE,
    created_by        VARCHAR(255),
    updated_by        VARCHAR(255),
    employee_id       BIGINT,
    over_time_rule_id BIGINT,
    tax_rule_id       BIGINT,
    base_salary       DECIMAL,
    effective_date    date,
    CONSTRAINT pk_employeesalary PRIMARY KEY (id)
);

CREATE TABLE holiday
(
    id            BIGINT NOT NULL,
    creation_time TIMESTAMP WITHOUT TIME ZONE,
    modified_time TIMESTAMP WITHOUT TIME ZONE,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    name          VARCHAR(255),
    date          date,
    type          VARCHAR(255),
    multiplier    DOUBLE PRECISION,
    CONSTRAINT pk_holiday PRIMARY KEY (id)
);

CREATE TABLE leave_request
(
    id            BIGINT NOT NULL,
    creation_time TIMESTAMP WITHOUT TIME ZONE,
    modified_time TIMESTAMP WITHOUT TIME ZONE,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    employee_id   BIGINT,
    leave_type_id BIGINT,
    start_date    date,
    end_date      date,
    status        VARCHAR(255),
    days          INTEGER,
    reason        VARCHAR(255),
    CONSTRAINT pk_leaverequest PRIMARY KEY (id)
);

CREATE TABLE leave_type
(
    id                BIGINT NOT NULL,
    creation_time     TIMESTAMP WITHOUT TIME ZONE,
    modified_time     TIMESTAMP WITHOUT TIME ZONE,
    created_by        VARCHAR(255),
    updated_by        VARCHAR(255),
    name              VARCHAR(255),
    is_paid           BOOLEAN,
    max_days_per_year INTEGER,
    CONSTRAINT pk_leavetype PRIMARY KEY (id)
);

CREATE TABLE over_time_rule
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_time TIMESTAMP WITHOUT TIME ZONE,
    modified_time TIMESTAMP WITHOUT TIME ZONE,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    name          VARCHAR(255),
    multiplier    DOUBLE PRECISION,
    description   VARCHAR(255),
    CONSTRAINT pk_overtimerule PRIMARY KEY (id)
);

CREATE TABLE payroll
(
    id                BIGINT NOT NULL,
    creation_time     TIMESTAMP WITHOUT TIME ZONE,
    modified_time     TIMESTAMP WITHOUT TIME ZONE,
    created_by        VARCHAR(255),
    updated_by        VARCHAR(255),
    employee_id       BIGINT,
    payroll_period_id BIGINT,
    basic_salary      DECIMAL,
    total_allowance   DECIMAL,
    overtime_pay      DECIMAL,
    holiday_pay       DECIMAL,
    leave_deduction   DECIMAL,
    late_deduction    DECIMAL,
    sss               DECIMAL,
    phil_health       DECIMAL,
    pagibig           DECIMAL,
    tax               DECIMAL,
    gross_salary      DECIMAL,
    net_salary        DECIMAL,
    CONSTRAINT pk_payroll PRIMARY KEY (id)
);

CREATE TABLE payroll_period
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_time TIMESTAMP WITHOUT TIME ZONE,
    modified_time TIMESTAMP WITHOUT TIME ZONE,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    start_date    date,
    end_date      date,
    status        VARCHAR(255),
    CONSTRAINT pk_payrollperiod PRIMARY KEY (id)
);

CREATE TABLE payroll_schedule
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_time TIMESTAMP WITHOUT TIME ZONE,
    modified_time TIMESTAMP WITHOUT TIME ZONE,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    name          VARCHAR(255),
    payroll_type  VARCHAR(255),
    pay_days      VARCHAR(255),
    CONSTRAINT pk_payrollschedule PRIMARY KEY (id)
);

CREATE TABLE payslip
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_time    TIMESTAMP WITHOUT TIME ZONE,
    modified_time    TIMESTAMP WITHOUT TIME ZONE,
    created_by       VARCHAR(255),
    updated_by       VARCHAR(255),
    employee_id      BIGINT,
    payroll_id       BIGINT,
    gross_salary     DECIMAL,
    total_deductions DECIMAL,
    net_salary       DECIMAL,
    CONSTRAINT pk_payslip PRIMARY KEY (id)
);

CREATE TABLE position
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_time TIMESTAMP WITHOUT TIME ZONE,
    modified_time TIMESTAMP WITHOUT TIME ZONE,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    title         VARCHAR(255),
    description   VARCHAR(255),
    CONSTRAINT pk_position PRIMARY KEY (id)
);

CREATE TABLE system_settings
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_time TIMESTAMP WITHOUT TIME ZONE,
    modified_time TIMESTAMP WITHOUT TIME ZONE,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    setting_key   VARCHAR(255),
    setting_value VARCHAR(255),
    description   VARCHAR(255),
    CONSTRAINT pk_systemsettings PRIMARY KEY (id)
);

CREATE TABLE tax_rule
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    creation_time TIMESTAMP WITHOUT TIME ZONE,
    modified_time TIMESTAMP WITHOUT TIME ZONE,
    created_by    VARCHAR(255),
    updated_by    VARCHAR(255),
    name          VARCHAR(255),
    rate          DOUBLE PRECISION,
    description   VARCHAR(255),
    CONSTRAINT pk_taxrule PRIMARY KEY (id)
);

ALTER TABLE department
    ADD CONSTRAINT uc_department_code UNIQUE (code);

ALTER TABLE employee_salary
    ADD CONSTRAINT uc_employeesalary_employee UNIQUE (employee_id);

ALTER TABLE system_settings
    ADD CONSTRAINT uc_systemsettings_settingkey UNIQUE (setting_key);

CREATE INDEX idx_attendance_employee ON attendance_log (employee_id);

CREATE INDEX idx_attendance_employee_timestamp ON attendance_log (employee_id, timestamp);

CREATE INDEX idx_attendance_timestamp ON attendance_log (timestamp);

ALTER TABLE attendance_log
    ADD CONSTRAINT FK_ATTENDANCELOG_ON_BIOMETRIC_DEVICE FOREIGN KEY (biometric_device_id) REFERENCES device (id);

ALTER TABLE attendance
    ADD CONSTRAINT FK_ATTENDANCE_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee (id);

ALTER TABLE deduction_bracket
    ADD CONSTRAINT FK_DEDUCTIONBRACKET_ON_DEDUCTIONTYPE FOREIGN KEY (deduction_type_id) REFERENCES deduction_type (id);

ALTER TABLE employee_allowance
    ADD CONSTRAINT FK_EMPLOYEEALLOWANCE_ON_ALLOWANCETYPE FOREIGN KEY (allowance_type_id) REFERENCES allowance_type (id);

ALTER TABLE employee_allowance
    ADD CONSTRAINT FK_EMPLOYEEALLOWANCE_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee (id);

ALTER TABLE employee_leave
    ADD CONSTRAINT FK_EMPLOYEELEAVE_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee (id);

ALTER TABLE employee_leave
    ADD CONSTRAINT FK_EMPLOYEELEAVE_ON_LEAVETYPE FOREIGN KEY (leave_type_id) REFERENCES leave_type (id);

ALTER TABLE employee_salary
    ADD CONSTRAINT FK_EMPLOYEESALARY_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee (id);

ALTER TABLE employee_salary
    ADD CONSTRAINT FK_EMPLOYEESALARY_ON_OVERTIMERULE FOREIGN KEY (over_time_rule_id) REFERENCES over_time_rule (id);

ALTER TABLE employee_salary
    ADD CONSTRAINT FK_EMPLOYEESALARY_ON_TAXRULE FOREIGN KEY (tax_rule_id) REFERENCES tax_rule (id);

ALTER TABLE employee
    ADD CONSTRAINT FK_EMPLOYEE_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES department (id);

ALTER TABLE employee
    ADD CONSTRAINT FK_EMPLOYEE_ON_PAYROLLSCHEDULECODE FOREIGN KEY (payroll_schedule_code_id) REFERENCES payroll_schedule (id);

ALTER TABLE employee
    ADD CONSTRAINT FK_EMPLOYEE_ON_POSITION FOREIGN KEY (position_id) REFERENCES position (id);

ALTER TABLE leave_request
    ADD CONSTRAINT FK_LEAVEREQUEST_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee (id);

ALTER TABLE leave_request
    ADD CONSTRAINT FK_LEAVEREQUEST_ON_LEAVETYPE FOREIGN KEY (leave_type_id) REFERENCES leave_type (id);

ALTER TABLE payroll
    ADD CONSTRAINT FK_PAYROLL_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee (id);

ALTER TABLE payroll
    ADD CONSTRAINT FK_PAYROLL_ON_PAYROLLPERIOD FOREIGN KEY (payroll_period_id) REFERENCES payroll_period (id);

ALTER TABLE payslip
    ADD CONSTRAINT FK_PAYSLIP_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee (id);

ALTER TABLE payslip
    ADD CONSTRAINT FK_PAYSLIP_ON_PAYROLL FOREIGN KEY (payroll_id) REFERENCES payroll (id);

-- Payroll Schedules
INSERT INTO payroll_schedule (id, name, payroll_type, pay_days)
VALUES (1, 'Weekly', 'WEEKLY', 'SATURDAY'),
       (2, 'Semi Monthly', 'SEMI_MONTHLY', '15,30'),
       (3, 'Monthly', 'MONTHLY', '30'),
       (4, 'Daily', 'DAILY', 'N\A') ON CONFLICT DO NOTHING;

-- Leave Types
INSERT INTO leave_type (id, name, is_paid, max_days_per_year)
VALUES (1, 'Annual Leave', true, 12),
       (2, 'Sick Leave', true, 15),
       (3, 'Unpaid Leave', false, 0),
       (4, 'Bereavement Leave', true, 10) ON CONFLICT DO NOTHING;

-- Deduction Types
INSERT INTO deduction_type (id, name, mandatory, rate)
VALUES (1, 'SSS', true, null),
       (2, 'PhilHealth', true, 100),
       (3, 'Pag-IBIG', false, 300) ON CONFLICT DO NOTHING;

-- Tax Rules
INSERT INTO tax_rule (id, name, description, rate)
VALUES (1, 'VAT', 'Goverment Tax', 0.25) ON CONFLICT DO NOTHING;

-- Deduction Types
INSERT INTO deduction_bracket (id, deduction_type_id, min_salary, max_salary, contribution)
VALUES (1, 1, 0, 50000, 3500) ON CONFLICT DO NOTHING;

-- Overtime Rules
INSERT INTO over_time_rule (id, name, multiplier)
VALUES (1, 'Regular OT', 1.25),
       (2, 'Special Holiday OT', 1.30),
       (3, 'Regular Holiday OT', 2.00) ON CONFLICT DO NOTHING;

-- Allowance Types
INSERT INTO allowance_type (id, name, taxable)
VALUES (1, 'Transport', false),
       (2, 'Meal', false),
       (3, 'Internet', false),
       (4, 'Housing', true) ON CONFLICT DO NOTHING;

-- Global Settings
INSERT INTO system_settings (description, setting_key, setting_value)
VALUES ('Start of work day', 'work.start.time', '09:00'),
       ('Overtime begins after this time', 'over.time.start', '18:00'),
       ('Minimum hours required per day', 'minimum.work.hours', 8) ON CONFLICT DO NOTHING;

-- Department
INSERT INTO department (id, code, description, name)
VALUES (1, 'IT', 'IT Staff', 'IT') ON CONFLICT DO NOTHING;

-- Position
INSERT INTO position (id, description, title)
VALUES (1, 'Senior Dev', 'Manager') ON CONFLICT DO NOTHING;

-- Employee Test Data
INSERT INTO employee (id, email, employee_code, first_name, last_name, status, hire_date, phone, department_id,
                      payroll_schedule_code_id, position_id)
VALUES (1, 'test', '1', 'John', 'Doe', 'active', '2026-03-12', '123',
        1, 1, 1),
       (2, 'test', '2', 'Jane', 'Doe', 'active', '2026-03-12', '123',
        1, 2, 1) ON CONFLICT DO NOTHING;
