name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'

    - name: Build and test
      run: mvn clean package -Dvaadin.productionMode=true -DskipTests

    - name: Build Docker image
      run: docker build -t hr-backoffice .

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker image
      run: |
        docker tag hr-backoffice ${{ secrets.DOCKERHUB_USERNAME }}/hr-backoffice:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/hr-backoffice:latest
